# docker-compose.yml
version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: buildbox
      POSTGRES_PASSWORD: bb_password
      POSTGRES_USER: bb_user
    ports:
      - 5435:5432
    restart: on-failure:3

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: postgres://bb_user:bb_password@postgres:5432/buildbox?sslmode=disable
    ports:
      - 8085:8081
    restart: on-failure:3
