version: "3"
dotenv: [".env"]

tasks:
  dev:
    cmds:
      - air
  format:
    cmds:
      - go fmt ./...
  tidy:
    cmds:
      - go mod tidy
  docs:
    cmds:
      - swag init --dir ./cmd
  build:
    cmds:
      - go build -o buildbox-api ./cmd
  docker:
    cmds:
      - docker compose up -d
  ent:new:
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent new {{.name}}
  migrate:lint:
    cmds:
      - atlas migrate lint --dir "file://ent/generated/migrate/migration" --dev-url "$POSTGRES_CONNECTION_STRING" --latest 1
  migrate:hash:
    cmds:
      - atlas migrate hash --dir "file://ent/generated/migrate/migration"
  migrate:new:
    desc: Create new migration file
    cmds:
      - atlas migrate new {{.name}} --dir "file://ent/generated/migrate/migration"
  migrate:status:
    desc: Run database migration
    cmds:
      - atlas migrate status --dir "file://ent/generated/migrate/migration" --url "$POSTGRES_CONNECTION_STRING"
  migrate:apply:
    desc: Run database migration
    cmds:
      - atlas migrate apply --dir "file://ent/generated/migrate/migration" --url "$POSTGRES_CONNECTION_STRING"
  start:
    cmds:
      - ./buildbox-api
  generate:
    desc: Runs all //go:generate commands embedded in .go files
    cmds:
      - go generate ./...
  install:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/go-task/task/v3/cmd/task@latest
