// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Pyakz/buildbox-api/ent/predicate"
	"github.com/Pyakz/buildbox-api/ent/project"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (pu *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetAccountID sets the "account_id" field.
func (pu *ProjectUpdate) SetAccountID(s string) *ProjectUpdate {
	pu.mutation.SetAccountID(s)
	return pu
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableAccountID(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetAccountID(*s)
	}
	return pu
}

// ClearAccountID clears the value of the "account_id" field.
func (pu *ProjectUpdate) ClearAccountID() *ProjectUpdate {
	pu.mutation.ClearAccountID()
	return pu
}

// SetClientID sets the "client_id" field.
func (pu *ProjectUpdate) SetClientID(s string) *ProjectUpdate {
	pu.mutation.SetClientID(s)
	return pu
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableClientID(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetClientID(*s)
	}
	return pu
}

// ClearClientID clears the value of the "client_id" field.
func (pu *ProjectUpdate) ClearClientID() *ProjectUpdate {
	pu.mutation.ClearClientID()
	return pu
}

// SetManagerID sets the "manager_id" field.
func (pu *ProjectUpdate) SetManagerID(s string) *ProjectUpdate {
	pu.mutation.SetManagerID(s)
	return pu
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableManagerID(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetManagerID(*s)
	}
	return pu
}

// ClearManagerID clears the value of the "manager_id" field.
func (pu *ProjectUpdate) ClearManagerID() *ProjectUpdate {
	pu.mutation.ClearManagerID()
	return pu
}

// SetCreatedBy sets the "created_by" field.
func (pu *ProjectUpdate) SetCreatedBy(s string) *ProjectUpdate {
	pu.mutation.SetCreatedBy(s)
	return pu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableCreatedBy(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetCreatedBy(*s)
	}
	return pu
}

// ClearCreatedBy clears the value of the "created_by" field.
func (pu *ProjectUpdate) ClearCreatedBy() *ProjectUpdate {
	pu.mutation.ClearCreatedBy()
	return pu
}

// SetName sets the "name" field.
func (pu *ProjectUpdate) SetName(s string) *ProjectUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetDescription sets the "description" field.
func (pu *ProjectUpdate) SetDescription(s string) *ProjectUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableDescription(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// ClearDescription clears the value of the "description" field.
func (pu *ProjectUpdate) ClearDescription() *ProjectUpdate {
	pu.mutation.ClearDescription()
	return pu
}

// SetNotes sets the "notes" field.
func (pu *ProjectUpdate) SetNotes(s string) *ProjectUpdate {
	pu.mutation.SetNotes(s)
	return pu
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableNotes(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetNotes(*s)
	}
	return pu
}

// ClearNotes clears the value of the "notes" field.
func (pu *ProjectUpdate) ClearNotes() *ProjectUpdate {
	pu.mutation.ClearNotes()
	return pu
}

// SetStatus sets the "status" field.
func (pu *ProjectUpdate) SetStatus(pr project.Status) *ProjectUpdate {
	pu.mutation.SetStatus(pr)
	return pu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableStatus(pr *project.Status) *ProjectUpdate {
	if pr != nil {
		pu.SetStatus(*pr)
	}
	return pu
}

// ClearStatus clears the value of the "status" field.
func (pu *ProjectUpdate) ClearStatus() *ProjectUpdate {
	pu.mutation.ClearStatus()
	return pu
}

// SetLocation sets the "location" field.
func (pu *ProjectUpdate) SetLocation(s string) *ProjectUpdate {
	pu.mutation.SetLocation(s)
	return pu
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableLocation(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetLocation(*s)
	}
	return pu
}

// ClearLocation clears the value of the "location" field.
func (pu *ProjectUpdate) ClearLocation() *ProjectUpdate {
	pu.mutation.ClearLocation()
	return pu
}

// SetBudget sets the "budget" field.
func (pu *ProjectUpdate) SetBudget(f float64) *ProjectUpdate {
	pu.mutation.ResetBudget()
	pu.mutation.SetBudget(f)
	return pu
}

// SetNillableBudget sets the "budget" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableBudget(f *float64) *ProjectUpdate {
	if f != nil {
		pu.SetBudget(*f)
	}
	return pu
}

// AddBudget adds f to the "budget" field.
func (pu *ProjectUpdate) AddBudget(f float64) *ProjectUpdate {
	pu.mutation.AddBudget(f)
	return pu
}

// ClearBudget clears the value of the "budget" field.
func (pu *ProjectUpdate) ClearBudget() *ProjectUpdate {
	pu.mutation.ClearBudget()
	return pu
}

// SetDeleted sets the "deleted" field.
func (pu *ProjectUpdate) SetDeleted(b bool) *ProjectUpdate {
	pu.mutation.SetDeleted(b)
	return pu
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableDeleted(b *bool) *ProjectUpdate {
	if b != nil {
		pu.SetDeleted(*b)
	}
	return pu
}

// ClearDeleted clears the value of the "deleted" field.
func (pu *ProjectUpdate) ClearDeleted() *ProjectUpdate {
	pu.mutation.ClearDeleted()
	return pu
}

// SetStartDate sets the "start_date" field.
func (pu *ProjectUpdate) SetStartDate(t time.Time) *ProjectUpdate {
	pu.mutation.SetStartDate(t)
	return pu
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableStartDate(t *time.Time) *ProjectUpdate {
	if t != nil {
		pu.SetStartDate(*t)
	}
	return pu
}

// ClearStartDate clears the value of the "start_date" field.
func (pu *ProjectUpdate) ClearStartDate() *ProjectUpdate {
	pu.mutation.ClearStartDate()
	return pu
}

// SetEndDate sets the "end_date" field.
func (pu *ProjectUpdate) SetEndDate(t time.Time) *ProjectUpdate {
	pu.mutation.SetEndDate(t)
	return pu
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableEndDate(t *time.Time) *ProjectUpdate {
	if t != nil {
		pu.SetEndDate(*t)
	}
	return pu
}

// ClearEndDate clears the value of the "end_date" field.
func (pu *ProjectUpdate) ClearEndDate() *ProjectUpdate {
	pu.mutation.ClearEndDate()
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProjectUpdate) SetUpdatedAt(t time.Time) *ProjectUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableUpdatedAt(t *time.Time) *ProjectUpdate {
	if t != nil {
		pu.SetUpdatedAt(*t)
	}
	return pu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (pu *ProjectUpdate) ClearUpdatedAt() *ProjectUpdate {
	pu.mutation.ClearUpdatedAt()
	return pu
}

// Mutation returns the ProjectMutation object of the builder.
func (pu *ProjectUpdate) Mutation() *ProjectMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProjectUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProjectUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProjectUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Status(); ok {
		if err := project.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Project.status": %w`, err)}
		}
	}
	return nil
}

func (pu *ProjectUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.AccountID(); ok {
		_spec.SetField(project.FieldAccountID, field.TypeString, value)
	}
	if pu.mutation.AccountIDCleared() {
		_spec.ClearField(project.FieldAccountID, field.TypeString)
	}
	if value, ok := pu.mutation.ClientID(); ok {
		_spec.SetField(project.FieldClientID, field.TypeString, value)
	}
	if pu.mutation.ClientIDCleared() {
		_spec.ClearField(project.FieldClientID, field.TypeString)
	}
	if value, ok := pu.mutation.ManagerID(); ok {
		_spec.SetField(project.FieldManagerID, field.TypeString, value)
	}
	if pu.mutation.ManagerIDCleared() {
		_spec.ClearField(project.FieldManagerID, field.TypeString)
	}
	if value, ok := pu.mutation.CreatedBy(); ok {
		_spec.SetField(project.FieldCreatedBy, field.TypeString, value)
	}
	if pu.mutation.CreatedByCleared() {
		_spec.ClearField(project.FieldCreatedBy, field.TypeString)
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if pu.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := pu.mutation.Notes(); ok {
		_spec.SetField(project.FieldNotes, field.TypeString, value)
	}
	if pu.mutation.NotesCleared() {
		_spec.ClearField(project.FieldNotes, field.TypeString)
	}
	if value, ok := pu.mutation.Status(); ok {
		_spec.SetField(project.FieldStatus, field.TypeEnum, value)
	}
	if pu.mutation.StatusCleared() {
		_spec.ClearField(project.FieldStatus, field.TypeEnum)
	}
	if value, ok := pu.mutation.Location(); ok {
		_spec.SetField(project.FieldLocation, field.TypeString, value)
	}
	if pu.mutation.LocationCleared() {
		_spec.ClearField(project.FieldLocation, field.TypeString)
	}
	if value, ok := pu.mutation.Budget(); ok {
		_spec.SetField(project.FieldBudget, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedBudget(); ok {
		_spec.AddField(project.FieldBudget, field.TypeFloat64, value)
	}
	if pu.mutation.BudgetCleared() {
		_spec.ClearField(project.FieldBudget, field.TypeFloat64)
	}
	if value, ok := pu.mutation.Deleted(); ok {
		_spec.SetField(project.FieldDeleted, field.TypeBool, value)
	}
	if pu.mutation.DeletedCleared() {
		_spec.ClearField(project.FieldDeleted, field.TypeBool)
	}
	if value, ok := pu.mutation.StartDate(); ok {
		_spec.SetField(project.FieldStartDate, field.TypeTime, value)
	}
	if pu.mutation.StartDateCleared() {
		_spec.ClearField(project.FieldStartDate, field.TypeTime)
	}
	if value, ok := pu.mutation.EndDate(); ok {
		_spec.SetField(project.FieldEndDate, field.TypeTime, value)
	}
	if pu.mutation.EndDateCleared() {
		_spec.ClearField(project.FieldEndDate, field.TypeTime)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if pu.mutation.UpdatedAtCleared() {
		_spec.ClearField(project.FieldUpdatedAt, field.TypeTime)
	}
	if pu.mutation.CreatedAtCleared() {
		_spec.ClearField(project.FieldCreatedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetAccountID sets the "account_id" field.
func (puo *ProjectUpdateOne) SetAccountID(s string) *ProjectUpdateOne {
	puo.mutation.SetAccountID(s)
	return puo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableAccountID(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetAccountID(*s)
	}
	return puo
}

// ClearAccountID clears the value of the "account_id" field.
func (puo *ProjectUpdateOne) ClearAccountID() *ProjectUpdateOne {
	puo.mutation.ClearAccountID()
	return puo
}

// SetClientID sets the "client_id" field.
func (puo *ProjectUpdateOne) SetClientID(s string) *ProjectUpdateOne {
	puo.mutation.SetClientID(s)
	return puo
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableClientID(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetClientID(*s)
	}
	return puo
}

// ClearClientID clears the value of the "client_id" field.
func (puo *ProjectUpdateOne) ClearClientID() *ProjectUpdateOne {
	puo.mutation.ClearClientID()
	return puo
}

// SetManagerID sets the "manager_id" field.
func (puo *ProjectUpdateOne) SetManagerID(s string) *ProjectUpdateOne {
	puo.mutation.SetManagerID(s)
	return puo
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableManagerID(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetManagerID(*s)
	}
	return puo
}

// ClearManagerID clears the value of the "manager_id" field.
func (puo *ProjectUpdateOne) ClearManagerID() *ProjectUpdateOne {
	puo.mutation.ClearManagerID()
	return puo
}

// SetCreatedBy sets the "created_by" field.
func (puo *ProjectUpdateOne) SetCreatedBy(s string) *ProjectUpdateOne {
	puo.mutation.SetCreatedBy(s)
	return puo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableCreatedBy(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetCreatedBy(*s)
	}
	return puo
}

// ClearCreatedBy clears the value of the "created_by" field.
func (puo *ProjectUpdateOne) ClearCreatedBy() *ProjectUpdateOne {
	puo.mutation.ClearCreatedBy()
	return puo
}

// SetName sets the "name" field.
func (puo *ProjectUpdateOne) SetName(s string) *ProjectUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetDescription sets the "description" field.
func (puo *ProjectUpdateOne) SetDescription(s string) *ProjectUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableDescription(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// ClearDescription clears the value of the "description" field.
func (puo *ProjectUpdateOne) ClearDescription() *ProjectUpdateOne {
	puo.mutation.ClearDescription()
	return puo
}

// SetNotes sets the "notes" field.
func (puo *ProjectUpdateOne) SetNotes(s string) *ProjectUpdateOne {
	puo.mutation.SetNotes(s)
	return puo
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableNotes(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetNotes(*s)
	}
	return puo
}

// ClearNotes clears the value of the "notes" field.
func (puo *ProjectUpdateOne) ClearNotes() *ProjectUpdateOne {
	puo.mutation.ClearNotes()
	return puo
}

// SetStatus sets the "status" field.
func (puo *ProjectUpdateOne) SetStatus(pr project.Status) *ProjectUpdateOne {
	puo.mutation.SetStatus(pr)
	return puo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableStatus(pr *project.Status) *ProjectUpdateOne {
	if pr != nil {
		puo.SetStatus(*pr)
	}
	return puo
}

// ClearStatus clears the value of the "status" field.
func (puo *ProjectUpdateOne) ClearStatus() *ProjectUpdateOne {
	puo.mutation.ClearStatus()
	return puo
}

// SetLocation sets the "location" field.
func (puo *ProjectUpdateOne) SetLocation(s string) *ProjectUpdateOne {
	puo.mutation.SetLocation(s)
	return puo
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableLocation(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetLocation(*s)
	}
	return puo
}

// ClearLocation clears the value of the "location" field.
func (puo *ProjectUpdateOne) ClearLocation() *ProjectUpdateOne {
	puo.mutation.ClearLocation()
	return puo
}

// SetBudget sets the "budget" field.
func (puo *ProjectUpdateOne) SetBudget(f float64) *ProjectUpdateOne {
	puo.mutation.ResetBudget()
	puo.mutation.SetBudget(f)
	return puo
}

// SetNillableBudget sets the "budget" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableBudget(f *float64) *ProjectUpdateOne {
	if f != nil {
		puo.SetBudget(*f)
	}
	return puo
}

// AddBudget adds f to the "budget" field.
func (puo *ProjectUpdateOne) AddBudget(f float64) *ProjectUpdateOne {
	puo.mutation.AddBudget(f)
	return puo
}

// ClearBudget clears the value of the "budget" field.
func (puo *ProjectUpdateOne) ClearBudget() *ProjectUpdateOne {
	puo.mutation.ClearBudget()
	return puo
}

// SetDeleted sets the "deleted" field.
func (puo *ProjectUpdateOne) SetDeleted(b bool) *ProjectUpdateOne {
	puo.mutation.SetDeleted(b)
	return puo
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableDeleted(b *bool) *ProjectUpdateOne {
	if b != nil {
		puo.SetDeleted(*b)
	}
	return puo
}

// ClearDeleted clears the value of the "deleted" field.
func (puo *ProjectUpdateOne) ClearDeleted() *ProjectUpdateOne {
	puo.mutation.ClearDeleted()
	return puo
}

// SetStartDate sets the "start_date" field.
func (puo *ProjectUpdateOne) SetStartDate(t time.Time) *ProjectUpdateOne {
	puo.mutation.SetStartDate(t)
	return puo
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableStartDate(t *time.Time) *ProjectUpdateOne {
	if t != nil {
		puo.SetStartDate(*t)
	}
	return puo
}

// ClearStartDate clears the value of the "start_date" field.
func (puo *ProjectUpdateOne) ClearStartDate() *ProjectUpdateOne {
	puo.mutation.ClearStartDate()
	return puo
}

// SetEndDate sets the "end_date" field.
func (puo *ProjectUpdateOne) SetEndDate(t time.Time) *ProjectUpdateOne {
	puo.mutation.SetEndDate(t)
	return puo
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableEndDate(t *time.Time) *ProjectUpdateOne {
	if t != nil {
		puo.SetEndDate(*t)
	}
	return puo
}

// ClearEndDate clears the value of the "end_date" field.
func (puo *ProjectUpdateOne) ClearEndDate() *ProjectUpdateOne {
	puo.mutation.ClearEndDate()
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProjectUpdateOne) SetUpdatedAt(t time.Time) *ProjectUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableUpdatedAt(t *time.Time) *ProjectUpdateOne {
	if t != nil {
		puo.SetUpdatedAt(*t)
	}
	return puo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (puo *ProjectUpdateOne) ClearUpdatedAt() *ProjectUpdateOne {
	puo.mutation.ClearUpdatedAt()
	return puo
}

// Mutation returns the ProjectMutation object of the builder.
func (puo *ProjectUpdateOne) Mutation() *ProjectMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (puo *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Project entity.
func (puo *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProjectUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Status(); ok {
		if err := project.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Project.status": %w`, err)}
		}
	}
	return nil
}

func (puo *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.AccountID(); ok {
		_spec.SetField(project.FieldAccountID, field.TypeString, value)
	}
	if puo.mutation.AccountIDCleared() {
		_spec.ClearField(project.FieldAccountID, field.TypeString)
	}
	if value, ok := puo.mutation.ClientID(); ok {
		_spec.SetField(project.FieldClientID, field.TypeString, value)
	}
	if puo.mutation.ClientIDCleared() {
		_spec.ClearField(project.FieldClientID, field.TypeString)
	}
	if value, ok := puo.mutation.ManagerID(); ok {
		_spec.SetField(project.FieldManagerID, field.TypeString, value)
	}
	if puo.mutation.ManagerIDCleared() {
		_spec.ClearField(project.FieldManagerID, field.TypeString)
	}
	if value, ok := puo.mutation.CreatedBy(); ok {
		_spec.SetField(project.FieldCreatedBy, field.TypeString, value)
	}
	if puo.mutation.CreatedByCleared() {
		_spec.ClearField(project.FieldCreatedBy, field.TypeString)
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if puo.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := puo.mutation.Notes(); ok {
		_spec.SetField(project.FieldNotes, field.TypeString, value)
	}
	if puo.mutation.NotesCleared() {
		_spec.ClearField(project.FieldNotes, field.TypeString)
	}
	if value, ok := puo.mutation.Status(); ok {
		_spec.SetField(project.FieldStatus, field.TypeEnum, value)
	}
	if puo.mutation.StatusCleared() {
		_spec.ClearField(project.FieldStatus, field.TypeEnum)
	}
	if value, ok := puo.mutation.Location(); ok {
		_spec.SetField(project.FieldLocation, field.TypeString, value)
	}
	if puo.mutation.LocationCleared() {
		_spec.ClearField(project.FieldLocation, field.TypeString)
	}
	if value, ok := puo.mutation.Budget(); ok {
		_spec.SetField(project.FieldBudget, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedBudget(); ok {
		_spec.AddField(project.FieldBudget, field.TypeFloat64, value)
	}
	if puo.mutation.BudgetCleared() {
		_spec.ClearField(project.FieldBudget, field.TypeFloat64)
	}
	if value, ok := puo.mutation.Deleted(); ok {
		_spec.SetField(project.FieldDeleted, field.TypeBool, value)
	}
	if puo.mutation.DeletedCleared() {
		_spec.ClearField(project.FieldDeleted, field.TypeBool)
	}
	if value, ok := puo.mutation.StartDate(); ok {
		_spec.SetField(project.FieldStartDate, field.TypeTime, value)
	}
	if puo.mutation.StartDateCleared() {
		_spec.ClearField(project.FieldStartDate, field.TypeTime)
	}
	if value, ok := puo.mutation.EndDate(); ok {
		_spec.SetField(project.FieldEndDate, field.TypeTime, value)
	}
	if puo.mutation.EndDateCleared() {
		_spec.ClearField(project.FieldEndDate, field.TypeTime)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if puo.mutation.UpdatedAtCleared() {
		_spec.ClearField(project.FieldUpdatedAt, field.TypeTime)
	}
	if puo.mutation.CreatedAtCleared() {
		_spec.ClearField(project.FieldCreatedAt, field.TypeTime)
	}
	_node = &Project{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
