// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Pyakz/buildbox-api/ent/project"
	"github.com/Pyakz/buildbox-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[4].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescDeleted is the schema descriptor for deleted field.
	projectDescDeleted := projectFields[10].Descriptor()
	// project.DefaultDeleted holds the default value on creation for the deleted field.
	project.DefaultDeleted = projectDescDeleted.Default.(bool)
	// projectDescStartDate is the schema descriptor for start_date field.
	projectDescStartDate := projectFields[11].Descriptor()
	// project.DefaultStartDate holds the default value on creation for the start_date field.
	project.DefaultStartDate = projectDescStartDate.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[13].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[14].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
}
