name: Atlas Lint
on:
  # Run whenever code is changed in the master branch,
  # change this to your root branch.
  push:
    branches:
      - main
  # Run on PRs where something changed under the `ent/migrate/migrations/` directory.
  pull_request:
    paths:
      - "ent/generated/migrate/migration/*"

jobs:
  lint:
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0 # Mandatory unless "latest" is set below.

      - uses: ariga/atlas-action@v0
        with:
          dir: ent/generated/migrate/migration
          dir-format: golang-migrate # Or: atlas, goose, dbmate
          dev-url: ${{ vars.DEV_URL }}
